### ISSUE TITLE
le pl est pas utilisable

### ISSUE THREAD

**Issue by TopeEstLa** [GaetanOff/Sanctions#1]
Hi

**Comment by GaetanOff** [comment]
Ce plugin est seulement un exemple, pour que le "développeur" Kayzun puisse enfin arriver à faire un /ss modulable via une config, sans donc faire de l’hard-code. Mais biensure je ne passerais pas mon framework, même si à vrai dire il ne comprendrais pas une ligne du framework.

**Comment by TopeEstLa** [comment]
![image](https://user-images.githubusercontent.com/51678715/118046312-6e6d3e80-b379-11eb-803b-f0b0fa6ebd81.png)

**Comment by GaetanOff** [comment]
Bah je ne peux pas connaitre l’erreur si le code ne vient pas de moi, je ne connais pas la manière dont le "plugin" a été codé. Mais bon en 20 minutes j’ai refait le plugin de 0 (en full modulable) et j’ai fait qu’une version comparer à ses 15 versions d’autant plus buggé.

Et d’ailleurs non sur WarnFight non plus ça ne fonctionnait pas

Certes j’ai fork Verus, mais bon il serait pas capable de comprendre 1% du code lui

**Comment by GaetanOff** [comment]
Et d’ailleurs non sur WarnFight non plus ça ne fonctionnait pas

**Comment by TopeEstLa** [comment]
Mais ducoup le pl il est pas utilisable bouuuuuuuuuu
